name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.13]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install msgpack-rpc-python backports.ssl_match_hostname
        gem install bundler
        bundle install
    - name: Run tests
      run: python -m unittest discover -v
